# Codex / Claude Code PostToolUse hook
# Fires after Edit / Write / MultiEdit. If the touched file is a .cs under
# Code/, run `dotnet build`. Failure -> exit 2 + stderr, surfaced to the agent
# as a blocking message; success -> exit 0 silently.
#
# Designed to enforce AGENTS.md non-negotiable #2 ("dotnet build apres
# changement runtime") without relying on the agent remembering.

$ErrorActionPreference = "SilentlyContinue"

# Read JSON payload from stdin. Codex/Claude Code sends one JSON object per
# invocation describing the tool call.
$stdinText = [Console]::In.ReadToEnd()
if ( -not $stdinText ) { exit 0 }

try {
    $payload = $stdinText | ConvertFrom-Json
} catch {
    exit 0
}

$path = $payload.tool_input.file_path
if ( -not $path ) { exit 0 }

# Only build for .cs files under Code/. Editor/ has its own assembly that
# the game .csproj does not cover; ignore it here.
$pathNorm = $path -replace '/', '\'
if ( $pathNorm -notmatch '\\Code\\.+\.cs$' ) { exit 0 }

# Debounce: if another hook fired the build < 2s ago, skip. The next edit
# in a parallel burst will catch up. Cheap, avoids dotnet lock contention
# on obj/ when the agent streams several edits in a single turn.
$lock = Join-Path $env:TEMP "tc-build-lock"
if ( Test-Path $lock ) {
    $age = (Get-Date) - (Get-Item $lock).LastWriteTime
    if ( $age.TotalSeconds -lt 2 ) { exit 0 }
}
[void](New-Item -Path $lock -ItemType File -Force)

$projectDir = $env:CODEX_PROJECT_DIR
if ( -not $projectDir ) { $projectDir = $env:CLAUDE_PROJECT_DIR }
if ( -not $projectDir ) { $projectDir = "C:\dev\tree-chopping-sbox" }
$proj = Join-Path $projectDir "Code\tree_chopping.csproj"

if ( -not (Test-Path $proj) ) {
    # csproj is gitignored / regenerated by sbox-dev. If missing, don't
    # block the agent -- just warn so the user can open the editor once.
    [Console]::Error.WriteLine("[hook:post-edit-build] csproj missing at $proj -- open sbox-dev once to regenerate, then this hook will re-engage.")
    exit 0
}

# Run the build. --nologo + minimal verbosity keeps the stderr feedback
# usable for the agent on failure.
$buildOutput = & dotnet build $proj --nologo --verbosity minimal 2>&1
$buildExit = $LASTEXITCODE

if ( $buildExit -eq 0 ) { exit 0 }

[Console]::Error.WriteLine("[hook:post-edit-build] dotnet build FAILED (exit $buildExit) after editing $path")
[Console]::Error.WriteLine("--- build output ---")
$buildOutput | ForEach-Object { [Console]::Error.WriteLine([string]$_) }
exit 2
